export const LoginPageLocators = {
  emailInput: 'input[data-qa="login-email"]',
  passwordInput: 'input[data-qa="login-password"]',
  loginButton: 'button[data-qa="login-button"]',
  loginError: '.login-form p',
  loginSuccessText: 'Logged in as',
  newUserSignUpNameInput: 'input[data-qa="signup-name"]',
  newUserSignUpEmailInput: 'input[data-qa="signup-email"]',
  newUserSignUpButton: 'button[data-qa="signup-button"]',
  newUserGenderMrRadioButton: '#id_gender1',
  newUserGenderMrsRadioButton: '#id_gender2',
  newUserNameInput: '[data-qa = "name"]',
  newUserPassword: 'input[data-qa = "password"]',
  newUserDayOBirthSelect: 'select[data-qa="days"]',
  newUserMonthOBirthSelect: 'select[data-qa = "months"]',
  newUserYearOBirthSelect: 'select[data-qa = "years"]',
  newUserNewsletterCheckbox: '[#newsletter]',
  newUserSpecialOfferCheckbox: '[#optin]',
  newUserFirstNameInput: 'input[data-qa = "first_name"]',
  newUserLastNameInput: 'input[data-qa = "last-name"]',
  newUserCompanyInput: 'input[data-qa = "company"]', 
  newUserAddressInput: 'input[data-qa = "address"]',
  newUserAddress2Input: 'input[data-qa = "address2"]',
  newUserCountrySelect: 'select[data-qa = "country"]',
  newUserStateInput: 'input[data-qa = "state"]',
  newUserCityInput: 'input[data-qa = "city"]',
  newUserZipcodeInput: 'input[data-qa = "zipcode"]',
  newUserMobileNumberInput: 'input[data-qa = "mobile_number"]',
  newUserCreateAccountButton: 'button[data-qa = "create-account"]',
  newUserContinueButton: 'button[data-qa = "continue-button"]'
};
